# -*- coding: utf-8 -*-
"""atividade_ru_ufrgs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rJi959XoWxzrEVhVzNsnK3gWdh4ByNYh
"""

# Guilherme da Silva Scher
# Ciência da Computação

"""
Restaurante Universitário da UFRGS

Objetivo:
- Implementar um sistema simples para gerenciar alunos e o uso de créditos no RU
- Cada aluno possui matrícula, nome e quantidade de créditos
- O RU controla o total de atendimentos liberados e negados por falta de crédito
- As funções permitem buscar um aluno pela matrícula e registrar o uso de refeição
- Ao final do código há um relatório exibindo o total de atendimentos concluídos e negados e a quantidade restante de créditos por aluno
"""

# Lista de alunos, cada aluno é representado por um dicionário
alunos = [
    {"matricula": "UFRGS2025001", "nome": "Scher", "creditos": 5},
    {"matricula": "UFRGS2025002", "nome": "Weber", "creditos": 0},
    {"matricula": "UFRGS2025003", "nome": "Otávio", "creditos": 3}
]

# Dicionário representando o RU
ru = {
    "nome": "Pasteka",
    "total_atendimentos": 0,
    "total_negados_sem_credito": 0
}

def encontrar_aluno(matricula):
    """Procura um aluno pela matrícula e retorna o dicionário ou None se não encontrar"""
    for aluno in alunos:
        if aluno["matricula"] == matricula:
            return aluno
    return None

def usar_refeicao(matricula):
    """Método usado para registar o uso de uma refeição, desconta crédito se houver ou nega se for zero."""
    aluno = encontrar_aluno(matricula)
    if aluno:
        if aluno["creditos"] >= 1:
            aluno["creditos"] -= 1
            print(f"Crédito debitado para {aluno['nome']}")
            ru["total_atendimentos"] += 1
        else:
            print(f"Recarregue seus créditos {aluno['nome']}")
            ru["total_negados_sem_credito"] += 1
    else:
        print(f"Erro! Matrícula {matricula} não existe")

# Simulação de eventos
usar_refeicao("UFRGS2025001")  # Sucesso (tinha crédito)
usar_refeicao("UFRGS2025002")  # Negado (sem crédito)
usar_refeicao("UFRGS2025003")  # Sucesso (tinha crédito)
usar_refeicao("UFRGS2025123")  # Matrícula inexistente

# Relatório Final
print(f"\nTotal de atendimentos: {ru['total_atendimentos']}")
print(f"Total de atendimentos negados: {ru['total_negados_sem_credito']}")
print("\nCréditos restantes por aluno:")
for aluno in alunos:
    print(f"{aluno['nome']}: {aluno['creditos']} créditos")