/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package algs;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author scher
 */
public class TelaOrdenacao extends javax.swing.JFrame {

    private GerenciadorArquivo gerenciadorArquivo = new GerenciadorArquivo();
    private AlgoritmosOrdenacao algoritmos = new AlgoritmosOrdenacao();
    private List<Integer> numeros;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaOrdenacao.class.getName());

    /**
     * Creates new form TelaOrdenacao
     */
    public TelaOrdenacao() {
        initComponents();
        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "bolha", "insercao", "selecao", "shell", "pente", "agitacao", "quick"
        }));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboMetodo = new javax.swing.JComboBox<>();
        btnCarregar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnCarregar.setText("Carregar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        jScrollPane1.setViewportView(areaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(comboMetodo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrdenar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCarregar)
                .addGap(18, 18, 18)
                .addComponent(comboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdenar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        if (gerenciadorArquivo.carregarArquivo()) {
            numeros = gerenciadorArquivo.getNumeros();
            areaResultado.setText("Arquivo carregado com " + numeros.size() + " números.");
        } else {
            areaResultado.setText("Nenhum arquivo carregado.");
        }
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        if (numeros == null || numeros.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Carregue um arquivo primeiro!");
            return;
        }

        String metodo = (String) comboMetodo.getSelectedItem();
        ResultadoOrdenacao resultado = algoritmos.ordenar(metodo, numeros);

        StringBuilder sb = new StringBuilder();
        sb.append("Método: ").append(resultado.getMetodo()).append("\n")
                .append("Tempo: ").append(resultado.getTempoExecucao()).append(" ms\n")
                .append("Comparações: ").append(resultado.getComparacoes()).append("\n")
                .append("Trocas: ").append(resultado.getTrocas()).append("\n")
                .append("Lista ordenada (primeiros 100 valores):\n");

        List<Integer> listaOrdenada = resultado.getListaOrdenada();
        for (int i = 0; i < Math.min(100, listaOrdenada.size()); i++) {
            sb.append(listaOrdenada.get(i)).append(" ");
        }

        areaResultado.setText(sb.toString());
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaOrdenacao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
